#nome completo = maiusculo e minusculo, quantas letras ao todo (sem considerar espaço e quantas letras tem o primeiro nome)
nome = input('Digite seu nome completo: ').strip()
print(f'Seu nome em maiúsculas: {nome.upper()}')
print(f'Seu nome em minúsculas: {nome.lower()}')
letras = len(nome.replace(' ', ""))
print(f'Seu nome tem ao todo: {letras} letras')
separa = nome.split()
letras_nome_1 = len(separa[0])
print(f'Seu primeiro nome é {separa[0]} e ele tem: {letras_nome_1} letras.')